kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: caddy-run
  labels:
    app: caddy-run
    template: caddy-bc-smk
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'caddy-run:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: 'alpine:3.8'
  postCommit: {}
  source:
    type: Dockerfile
    dockerfile: >-
      FROM alpine:3.8

      #USER root

      ENV ENABLE_TELEMETRY="false"

      WORKDIR /app

      RUN apk add --no-cache git openssh-client \
       && adduser -S smk \
       && chown -R smk:0 /app && chmod -R 770 /app
      USER smk

      EXPOSE 8080

      ENTRYPOINT ["/bin/parent", "caddy"]

      CMD ["--conf", "/conf/Caddyfile", "-quic"]

  runPolicy: Serial
