name: qa_push

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: test
    - name: Send Payload to openshift to trigger build
      run: |
        curl -H "Content-Type: application/json" -X POST -d @$GITHUB_EVENT_PATH ${{ secrets.TEST_WEBHOOK_URL }}
